### ISSUE TITLE
Semconv schema: formalize registry definition

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1269]
Today we require all attribute definitions to happen in the registry, i.e. :
- attribute definitions should be in `/model/registry` 
- the group id must start with `registry.`

We should consider having a more formal way to mark a group as one defining something.
E.g. 

```yaml
groups:
- id: foo.bar
  type: attribute_registry <-------- this is new
```

or 

```yaml
groups:
- id: new-guid
  type: metric_registry <-------- this is new
```

This would simplify filtering/massaging semconv in code-generation, we'd avoid relying on specific group naming. 
This would move post-factum policies enforcing attribute definitions into schema validation (`id` can only appear on `*_registry` groups and `ref` cannot appear there).
