### ISSUE TITLE
Don't require brief for deprecated attributes, auto-generate it in markdown and code

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1419]
We currently do this: 

```yaml
brief: 'Deprecated, use `server.address`, `server.port` attributes instead.'
deprecated: "Replaced by `server.address` and `server.port`."
```

It'd be nice to avoid duplication - https://github.com/open-telemetry/semantic-conventions/pull/1418#discussion_r1766981411

**Comment by lmolkova** [comment]
Syntax suggestion:

```yaml
- id: registry.foo.deprecated 
  ...
  attributes:
    - id:  foo.id
      deprecated:
        renamed_to: foo.unique_id
        note: >
          Optional note to provide any other info
    - id:  foo.another_attribute
      deprecated: removed
```
