### ISSUE TITLE
Automate schema-next generation

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#1426]
[schema-next](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) contains a list of transformations to apply to attribute/metrics/event/resource to convert them from previous version to current one.

It relies on contributors and reviewers to update it manually and there is no check that verifies that file was updated and that it's a valid transformation (both attributes/metrics/etc exist, the type is the same, etc).

We can automate generation of this file if we formalize it in yaml.

1. Attribute/metric/event rename is applied along with deprecation (#1419). We can formalize deprecation and update schema-next automatically.

    ```yaml
    - id: registry.foo.deprecated 
      ...
      attributes:
        - id:  foo.id
          deprecated:
            renamed_to: foo.unique_id
            note: >
              Optional note to provide any other info
        - id:  foo.another_attribute
          deprecated: removed
    ```

   This would cover all of the existing cases we support in `schema-next.yaml`.

2. There are changes that we don't yet have transformation defined for that don't involve deprecation - for those we probably need to analyze the diff between versions:
    - attribute type/metric unit or instrument was changed
    - default value has changed
    - ...

    For this category we can also look into combining it with the changelog - changelog could be auto-generated based on the actual diff. Or changelog format can be made more specific so that we can generate transformations from it.

Arguably, we need a combination of changelog and semantic conventions to be available to the codegen as well (e.g. if attribute type has changed, I might want to generate some extra documentation, do something custom like type conversion, or maybe get alerted in some custom way.

**Comment by lquerel** [comment]
Thanks, Liudmila, for specifying this. With that in place in semconv, Weaver will be able to automatically update the OTEL schema for any future version of the registry.

I would suggest using a representation similar to renaming for the removal of attributes, as it's possible to include a note for both removal and renaming.

```yaml
- id: registry.foo.deprecated 
  ...
  attributes:
    - id:  foo.id
      deprecated:
        renamed_to: foo.unique_id
        note: >
          Optional note to provide any other info
    - id:  foo.another_attribute
      deprecated: 
        removed: true
        note: >
          Removed, report shared memory usage with `metric.system.memory.shared` metric
```

Another option, which could be grammatically more regular, might be…

```yaml
- id: registry.foo.deprecated 
  ...
  attributes:
    - id: foo.id
      deprecated:
        action: renamed
        renamed_to: foo.unique_id
        note: >
          Optional note to provide any other info
    - id: foo.another_attribute
      deprecated:
        action: removed
        note: >
          Optional note to provide any additional info about the removal
```

**Comment by lmolkova** [comment]
We use the following trick for `requirement_level`:

```yaml
- id: attr.one 
  requirement_level: recommended
- id: attr.two
  requirement_level: 
    recommended: some optional note
```

Not sure what we do on the weaver side and if we're able to preserve the note to the codegen. If we can, than we should reuse the same trick. If not, we should fix it in some way.
