### ISSUE TITLE
Proposal: Add Sensitive Data Labels

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/semantic-conventions#1594]
## The Pitch
The idea is rather simple, extending the current OTLP to include an additional dictionary that is intended to store sensitive data. 

## The Rationale
Making the use of sensitive data being explicit instead implicit means that data vendors, data processors (pre and post) can first of all:
- Ensure any data regulations are followed (Thinking GDPR, CCPA, FedRamp to a degree)
- Allow for consumers of this data to handle the data correctly 

As we collect more telemetry from user's experiences, the likelihood of including UGC and PII increases and this should help those system that collect it to be clear on the actions they take on it.

## The outcome
The idea I have in mind and would love further discussion on is how this is consumed by the client (the application actually sending the data).

The idea being that the OTLP is extending to include another dictionary that is explicit in its sensitive nature and the SDK implement a `AddSensitiveLabel` method to make it clear on what it is.

From that the otel-collector could filter, drop, or transform those labels if they are known. 

From there, the exported data vendors / processes can set up ingestion policies on what should happen when sensitive data arrives.

**Comment by lmolkova** [comment]
I believe it can be done today with annotations:

```yaml
- id: sensitive.attribute
  annotations:
    sensitivity: PII | secrets | all | none  # need to define and polish this enum
    reduction:  # this could be added later, need some design
      strategy: drop  # more strategies can be defined, e.g. regex, `strategy` serves as a discriminator for `reduction` type
```
