### ISSUE TITLE
Consider adding JVM metric for open file descriptors Semantic Conventions

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/semantic-conventions#1838]
### Propose new conventions

I'd like to add this metric to the [java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib/) project. 

<img width="896" alt="Image" src="https://github.com/user-attachments/assets/6d2635bb-c9c9-4819-a002-455b49131c5f" />

```yaml
  - bean: java.lang:type=OperatingSystem
    mapping:
      OpenFileDescriptorCount:
        metric: jvm.fd.open
        unit: 1
        desc: open file descriptors
```

Happy to discuss naming conventions on these as well but would like to collect this information!

I believe that this metric would be useful for monitoring resource usage and detecting potential file descriptor leaks and should be recommended metric. 

Apologies if there was already discussion on adding this metric I just did not see it in the current list found here: https://opentelemetry.io/docs/specs/semconv/runtime/jvm-metrics/
