### ISSUE TITLE
Add metric category information

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/semantic-conventions#2165]
**What are you trying to achieve?**
Metric collection right now is mostly working with boolean flags in the collector and specific integration names in SDKs.
I would like to be able to turn on and off metrics, as well as filter or prioritize them, based on category metadata.

What did you expect to see?
I expect that metric definition would carry category information.
An example of metric definition is by mdatagen in the collector where the metric category would be defined in yaml format:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/metadata.yaml

```
postgresql.bgwriter.buffers.allocated:
    description: Number of buffers allocated.
    enabled: true
    sum:
      aggregation_temporality: cumulative
      monotonic: true
      value_type: int
    unit: "{buffers}"
```

I would want to add additional metadata to the metric definition:

```
postgresql.bgwriter.buffers.allocated:
    description: Number of buffers allocated.
    categories:
      - postgresql
      - database
      - scraper
    enabled: true
    sum:
      aggregation_temporality: cumulative
      monotonic: true
      value_type: int
    unit: "{buffers}"
```

I would like to see the same logic applied to all metrics such as SDK metrics, so end users can set this information via uniform configuration. The categories should be defined in a central location such as the specification repository, the configuration as part of the configuration SIG.
