### ISSUE TITLE
Should HTTP client metrics have url.scheme?

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#356]
[HTTP Client metrics](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration) do not have a scheme:

- scheme may be useful to break traffic down by http/https
- more importantly, we populate port based on scheme

```yaml
  - ref: server.port
    requirement_level:
      conditionally_required: If not default (`80` for `http` scheme, `443` for `https`).
```

Populating port alone won't be sufficient since we still won't know the scheme used.
