### ISSUE TITLE
Disambiguate attribute deprecation

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions#582]
There are currently two ways to deprecate at attribute:
1. By setting stability to deprecated
    ```yaml
    - id: status_code
      brief: 'Deprecated, use `http.response.status_code` instead.'
      stability: deprecated
      ....
    ```
2. By providing `deprecated: description` property
    ```yaml
    - id: status_code
      deprecated: "use `http.response.status_code` instead."
    ```

The first approach is problematic: once attribute is deprecated it's no longer possible to know what was the stability at deprecation time. 
It's problematic for code generation:
- I want to separate experimental and stable attributes into different artifacts (or packages) based on stability level - I no longer know where to put deprecated ones (where they used to be)
- I want to drop deprecated attributes that were experimental at deprecation time and only keep ones that were stable at deprecation time - I'm not able to do it.

Related to #551
