### ISSUE TITLE
Add k8s.container.status.last_terminated_reason to semantic conventions.

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/semantic-conventions#922]
### Area(s)

area:k8s

### Is your change request related to a problem? Please describe.

We recently added `k8s.container.status_last_terminated_reason` to kubernetes cluster receiver. And we would like to add resource attribute ~`k8s.container.status_last_terminated_reason`~ to existing semantic conventions.

**Edit: It was agreed that this attribute is better named  `k8s.container.status.last_terminated_reason`** 

Reference https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31505#discussion_r1521881960

Also issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31282

### Describe the solution you'd like

Add resource attribute `k8s.container.status_last_terminated_reason` to existing semantic conventions.

**Comment by joaopgrassi** [comment]
Given the example and structure is complex for `status`

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31282#issue-2136401464

kubectl get pod X -o yaml

```
apiVersion: v1
kind: Pod
...
status:
  containerStatuses:
  - containerID: containerd://07ff7db2706d20ddd26c6257c1c1dbf176917f855c7feef0e05db88159b1584d
    image: image
    imageID:  imageId
    lastState:
      terminated:
        containerID: containerid
        exitCode: 2
        finishedAt: "2024-02-05T23:17:38Z"
        reason: Error
        startedAt: "2024-02-05T23:17:33Z"
```

I think we should probably have it more structured. Maybe something like `k8s.container.status.last_terminated_reason`. Because then we could add more things under status, such as  the container id and etc. 

You also added a metric to the collector, right? This metric should also probably be added to the semconv.
