### ISSUE TITLE
Add `name` property on registry attribute groups

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/semantic-conventions#978]
In order to automatically render readable titles for generated attributes registry docs, it would be useful to have display names for attribute groups in the YAML files (see https://github.com/open-telemetry/semantic-conventions/pull/917#discussion_r1580512059).

Proposal is to add a property `name` (or `display_name` or `title`) to each attributes group in the registry so that the weaver can use that property for rendering headings. 

Example:

```

groups:
  - id: registry.aws.dynamodb
    prefix: aws.dynamodb
    type: attribute_group
    name: AWS DynamoDB
    brief: >
            This document defines attributes for AWS DynamoDB.
    attributes:
         ...
```
