### ISSUE TITLE
add k8s.container.status.waiting_reason resource attribute

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/semantic-conventions#996]
### Is your change request related to a problem? Please describe.

Original request to add such attribute in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32457

Basically user wants to monitor/alert CrashLoopBackOff reason.

Example Pod in such state:
```
  containerStatuses:
  - containerID: containerd://6bb73f56d9f34abc2015629d594625e8e637582ecf94b7e5067171c647a773fd
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:ed6d2c43c8fbcd3eaa44c9dab6d94cb346234476230dc1681227aa72d07181ee
    lastState:
      terminated:
        containerID: containerd://6bb73f56d9f34abc2015629d594625e8e637582ecf94b7e5067171c647a773fd
        exitCode: 0
        finishedAt: "2024-05-02T12:30:53Z"
        reason: Completed
        startedAt: "2024-05-02T12:30:41Z"
    name: test
    ready: false
    restartCount: 2
    started: false
    state:
      waiting:
        message: back-off 20s restarting failed container=test pod=dns-example_default(dbd4171d-fcef-45d5-8caf-be07213e1bf6)
        reason: CrashLoopBackOff
```

### Describe the solution you'd like

Add  k8s.container.status.waiting_reason resource attribute.
